package com.mohsenfallah.goldwidget;
import android.app.*; import android.appwidget.*; import android.content.*; import android.widget.*; import java.text.*; import java.util.*; import java.util.concurrent.*;
public class GoldWidgetProvider extends AppWidgetProvider {
 private static final String REFRESH="com.mohsenfallah.goldwidget.REFRESH"; private static final ExecutorService EXEC=Executors.newSingleThreadExecutor(); private static final DecimalFormat NUM=new DecimalFormat("#,##0",DecimalFormatSymbols.getInstance(Locale.US));
 @Override public void onUpdate(Context c,AppWidgetManager m,int[] ids){refresh(c);}
 @Override public void onReceive(Context c,Intent i){super.onReceive(c,i); if(REFRESH.equals(i.getAction()))refresh(c);}
 private void refresh(Context c){final PendingResult p=goAsync(); EXEC.execute(()->{try{TgjuRepository.Data d=TgjuRepository.fetch(); updateAll(c,d,null);}catch(Exception e){updateAll(c,null,"خطا در دریافت اطلاعات");}finally{p.finish();}});}
 private void updateAll(Context c,TgjuRepository.Data d,String err){AppWidgetManager m=AppWidgetManager.getInstance(c); int[] ids=m.getAppWidgetIds(new ComponentName(c,GoldWidgetProvider.class)); for(int id:ids)update(c,m,id,d,err);}
 private void update(Context c,AppWidgetManager m,int id,TgjuRepository.Data d,String err){RemoteViews v=new RemoteViews(c.getPackageName(),R.layout.widget_gold); if(d!=null){v.setTextViewText(R.id.val_gold18,money(d.gold18));v.setTextViewText(R.id.val_gold24,money(d.gold24));v.setTextViewText(R.id.val_coin,money(d.coin));v.setTextViewText(R.id.val_dollar,money(d.dollar));v.setTextViewText(R.id.val_tether,money(d.tether));v.setTextViewText(R.id.val_ounce,dec(d.ounce));v.setTextViewText(R.id.val_silver,dec(d.silver));double real24=d.ounce*d.dollar/31.1034768;v.setTextViewText(R.id.val_real24,money(real24));v.setTextViewText(R.id.val_real18,money(real24*.75));v.setTextViewText(R.id.txt_update,"آخرین بروزرسانی: "+new SimpleDateFormat("HH:mm",Locale.US).format(new Date()));}else v.setTextViewText(R.id.txt_update,err); Intent i=new Intent(c,GoldWidgetProvider.class);i.setAction(REFRESH);PendingIntent pi=PendingIntent.getBroadcast(c,id,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);v.setOnClickPendingIntent(R.id.widget_root,pi);m.updateAppWidget(id,v);}
 private static String money(double x){return NUM.format(Math.round(x))+" تومان";} private static String dec(double x){return new DecimalFormat("#,##0.00",DecimalFormatSymbols.getInstance(Locale.US)).format(x)+" $";}
}